env:
  es6: true
  browser: true
  node: true

rules:
  curly: 0
  comma-dangle: [2, 'always-multiline']
  comma-spacing: 0
  eqeqeq: [2, 'allow-null']
  key-spacing: 0
  max-len: [1, 140]
  no-console: 1
  no-underscore-dangle: 0
  no-unused-expressions: 0
  no-shadow: 0
  no-shadow-restricted-names: 0
  no-extend-native: 0
  no-unused-vars:
    - error
    - varsIgnorePattern: '^_'
      argsIgnorePattern: '^_'
  no-var: 2
  new-cap: 1
  quotes: 1
  semi-spacing: 1
  space-unary-ops: 1
  space-infix-ops: 1
  consistent-return: 1
  strict: 1
  import/prefer-default-export: 0
  react/jsx-filename-extension: 0
  react/forbid-prop-types:
    - 1
    - forbid:
      - any
      - array

parser: 'babel-eslint'

plugins:
  - react
  - jsx-a11y
  - redux-saga
  - you-dont-need-lodash-underscore

extends: airbnb

ecmaFeatures:
  arrowFunctions: true
  jsx: true

globals:
  API_BASE_URL: true

settings:
  import/resolver: 'babel-module'
